### ISSUE TITLE
[DS] Architecture 

### ISSUE THREAD

**Issue by eunchan-park** [skkuse02/2019fall_41class_team3#18]
Architecture for design specification

**Comment by devAdaid** [comment]
수업시간에 논의한 아키텍처 초안

![1_User](https://user-images.githubusercontent.com/16263530/68447340-edccff80-0222-11ea-8e09-ac6a7a0e3025.jpg)
![2_Question](https://user-images.githubusercontent.com/16263530/68447343-f1608680-0222-11ea-8a21-a0fbafd69dba.jpg)
![3_Live chat video](https://user-images.githubusercontent.com/16263530/68447347-f3c2e080-0222-11ea-9cbb-2b89055d4d64.jpg)

**Comment by devAdaid** [comment]
취합 완료 했습니다 :)
