### ISSUE TITLE
[DS] Introduction / Testing

### ISSUE THREAD

**Issue by eunchan-park** [skkuse02/2019fall_41class_team3#21]
Introduction / Testing for design specification

**Comment by D-Sinus** [comment]
2. Introduction (Done, Uploaded on Google Drive)
2-1. Objectives
2-2. Applied Diagrams
2-3. Applied Tools

[Add] 'Socket.io' to 'Applied Tools' list
[Add] 'Visual Paradigm' to 'Applied Tools' list (19/11/11 PM 05:00)

**Comment by D-Sinus** [comment]
8. Testing Plan (Done, Uploaded on Google Drive)
8-1. Objectives
8-2. Test Process
8-3. Test Cases

**Comment by devAdaid** [comment]
취합 완료 했습니다 :)
